wiilog/wiistock

config/services.yaml

>>>>>> V 6.27.3

---

src/Service/IOT/IOTService.php

Le capteur envoie des messages qui étaient mal interprétés. Nous avons ajouté une vérification pour ignorer ces messages

WIIS-9919 IoT | Relevés de températures anormales

---

src/Controller/ArticleController.php
src/Entity/Article.php
templates/article/form/form.html.twig

WIIS-10044

---

src/Controller/PackController.php
src/Repository/PackRepository.php
src/Service/TrackingMovementService.php

WIIS-10065

---

src/Controller/Settings/SettingsController.php
src/Controller/Settings/StatusController.php

REG I WEB I Paramétrage I Statuts I Acheminements

WIIS-10067

---

migrations/Version20230721121721.php

Correction de la migration Version20230721121721.php, ajout de la table reserve si elle n'existe pas

WIIS-10002

---

src/Controller/LivraisonController.php

WEB I Ordre livraison avec UL I Impossible de générer le BL

WIIS-10083

---

src/Controller/DispatchController.php
src/Entity/Statut.php
src/Repository/DispatchRepository.php

WIIS-10152

---

src/Entity/Dispatch.php

ORM | Acheminements - Nouveaux champs dans l'entité Dispatch
Ajout des champs suivants :
customerName (varchar, nullable)
customerPhone (varchar, nullable)
customerAddress (text, nullable)
customerRecipient (varchar, nullable)

WIIS-10140

---

.env
src/Controller/Api/Mobile/MobileController.php
src/Controller/SecuriteController.php
src/Controller/Settings/UserController.php
src/Entity/SessionHistoryRecord.php
src/Entity/Utilisateur.php
src/Repository/SessionHistoryRecordRepository.php
src/Repository/UtilisateurRepository.php
src/Service/SessionHistoryRecordService.php

Licences CEA : Nomade - Gestion des licences à la connexion

WIIS-10113

---

src/Controller/Api/Mobile/MobileController.php
src/Entity/SessionHistoryRecord.php

Licences CEA : Nomade - Gestion des licences à la déconnexion

WIIS-10115

---

src/Command/CloseAllSessionsCommand.php
src/Command/CloseInactivesSessionsCommand.php
src/Entity/UserSession.php
src/Service/SessionHistoryRecordService.php

Licences CEA : Commande Symfony permettant de fermer une session grâce à une clé de session fournie

WIIS-10118

---

assets/js/pages/settings/index.js
assets/js/pages/settings/users/licences.js
src/Command/sessions/CloseAllSessionsCommand.php
src/Command/sessions/CloseInactivesSessionsCommand.php
src/Command/sessions/CloseSessionsCommand.php
src/Controller/Api/Mobile/MobileController.php
src/Controller/SessionHistoryRecordController.php
src/Repository/SessionHistoryRecordRepository.php
src/Security/UserChecker.php
templates/settings/utilisateurs/licences.html.twig

Licences : Paramétrages | Utilisateurs | Licences : créer la nouvelle page de licence + faire la liste

WIIS-10108

---

src/Service/DispatchService.php

WIIS-10285

---

public/js/pages/preparation-show.js

REG I WEB I Ordre préparation - message d'erreur

WIIS-10325

---

src/Service/ImportService.php

WEB - Paramétrage | Import - Réception : Impossible d'importer des réceptions : Erreur 500

WIIS-10320

---

assets/js/pages/delivery-request/show.js
src/Controller/DemandeController.php
templates/demande/modalEditDemande.html.twig
templates/demande/modalEditDemandeContent.html.twig

WEB - Demande | Livraison : Les champs se vident si rempli puis sorti de la demande puis rerentrer

WIIS-10384

---

src/Controller/ArticleController.php
src/Service/ArticleDataService.php

WEB - Stock | Articles | Création articles : Les champs se vident si rempli lors de la création et non affichés à la modif ..

WIIS-10372

---

assets/js/ajax.js
src/Controller/ArrivageController.php

Enlever remonté de log sur les étiquettes arrivage

WIIS-10374

---

src/Entity/TrackingMovement.php
templates/mouvement_traca/index.html.twig
templates/mouvement_traca/modalNewMvtTraca.html.twig

Traçabilité | Mouvements | Formulaire - Positionner le select de type par défaut sur "Prises et déposes"

WIIS-10353

---

src/Controller/IOT/DataHistoryController.php
src/Controller/IOT/PairingController.php
src/Controller/Transport/OrderController.php
src/Controller/Transport/RequestController.php
src/Entity/IOT/PairedEntity.php
src/Entity/IOT/SensorMessageTrait.php
src/Entity/Transport/TransportDeliveryRequestLine.php
src/Service/Transport/TransportRoundService.php
src/Service/Transport/TransportService.php

Bug affichage courbe de température.
Erreur 500 sur la création de demande de transport

WIIS-10406 && WIIS-10505

---

migrations/Version20231031093913.php
src/Controller/DispatchController.php
src/Controller/NatureController.php
src/Entity/Nature.php
src/Repository/NatureRepository.php
src/Service/DispatchService.php
src/Service/NatureService.php
templates/nature_param/modalEditNatureContent.html.twig
templates/nature_param/modalNewNature.html.twig

WIIS-10503 - [Standard] Référentiel | Nature - Rajouter champ

WIIS-10503

---

public/js/pages/arrival/show.js

REG WEB I Arrivage UL I Acheminer I message d'erreur

WIIS-10573

---

src/Controller/NatureController.php
src/Entity/Nature.php
templates/nature_param/modalDeleteNatureRight.html.twig
templates/nature_param/modalDeleteNatureWrong.html.twig

REG WEB I Référentiel I Nature I suppression ne fonctionne pas

WIIS-10572

---

src/Controller/SelectController.php
src/Entity/Fields/FixedField.php
src/Entity/Fields/FixedFieldByType.php
src/Repository/DispatchRepository.php
templates/filters/filtersDispatchs.html.twig

WEB - Standard - Paramétrages | Trace | Acheminements | Configuration : Champs filtres ne fonctionnent pas tous

WIIS-10588

---

src/Controller/DispatchController.php
templates/settings/trace/acheminements/configurations.html.twig

WEB  - Paramétrages | Trace | Acheminements | Configuration : Fonctionnel de "Validation d'un acheminement"

WIIS-10585

---

templates/arrivage/modalListPacksContent.html.twig

WIIS-10631

---

templates/prints/deliveryNoteTemplate.html.twig
templates/prints/deliveryNoteTemplateHeader.html.twig

WIIS-10612

---

templates/prints/dispatchLabelTemplate.html.twig

WIIS-10684

---

src/Service/DispatchService.php

Acheminements I Liste UL I Ordre d'affichage des champs Longueur, Largeur, Hauteur:
Afficher les champs dans cet ordre:  Longueur, Largeur, Hauteur

WIIS-10683

---

templates/settings/trace/acheminements/bon_surconsommation.html.twig

WIIS-10625

---

src/Service/SettingsService.php

WIIS-10673

---

src/Controller/ArrivageController.php

WIIS-10667

---

src/Controller/ReceiptAssociationController.php
src/Service/ReceiptAssociationService.php

WEB I Association BR I Message d'erreur quand on enregistre avec unité logistique non existante

WIIS-10853

---

src/Controller/TriggerActionController.php
templates/trigger_action/actions.html.twig
templates/trigger_action/edit_content_modal.html.twig
templates/trigger_action/modalTracer.html.twig

WEB I IOT I Actionneurs I Modification d'un actionneur de type "Dépose sur emplacement"

WIIS-10879

---

assets/js/pages/reception/show.js
public/js/pages/arrival/show.js
public/js/pages/litiges.js
src/Controller/DisputeController.php

WEB | Qualité  Litige => historique : Le tri de l'historique

WIIS-10837

---

config/services.yaml
src/Entity/TrackingMovement.php
src/EventListener/TrackingMovementListener.php
src/Service/MailerService.php
src/Service/TrackingMovementService.php
templates/mails/contents/mailDropLuOnLocation.html.twig

Référentiel | Emplacements - Faire template + appliquer l'envoi d'emails

WIIS-10889

---

assets/js/pages/production/form.js
assets/js/pages/production/index.js
assets/js/pages/production/show.js
templates/production_request/index.html.twig
templates/production_request/modal/form.html.twig
templates/production_request/show/index.html.twig

Demande de production : la pj obligatoire sur un statut ne fonctionne pas..

WIIS-10960

---

assets/js/pages/location/index.js
assets/js/pages/reference-article/index.js
assets/js/pages/settings/index.js
assets/js/pages/truck-arrival/show.js
public/js/pages/cart.js
public/js/pages/pack.js
src/Controller/CartController.php
src/Controller/CustomerController.php
src/Controller/FiltreRefController.php
src/Controller/GroupController.php
src/Controller/TruckArrivalController.php
src/Controller/ZoneController.php
templates/customer/index.html.twig
templates/header.html.twig
templates/truck_arrival/index.html.twig

Traçabilité | Arrivage camion : Le numéro de tracking disparait si déjà sur un autre arrivage non associé

WIIS-10984

---

templates/production_request/modal/form.html.twig
templates/production_request/modal/new.html.twig

[WEB] Demande | Production : Changement de l'ordre d'affichage des champs de la modale.

WIIS-11079

---

templates/emplacement/form/form.html.twig

Référentiel | Emplacement : Impossible de rendre inactif

WIIS-11100

---

public/js/pages/trigger_action/index.js
src/Controller/TriggerActionController.php
templates/trigger_action/edit_content_modal.html.twig

[WEB] IOT : Actionneur : la modale de modif d'un actionneur n'est pas à jour avec les infos de la création

WIIS-10975

---

src/Service/PDFGeneratorService.php
src/Service/SettingsService.php

ORDRE | RECEPTION | DETAILS Problème génération étiquette
Le nom du fichier contanais un /

WIIS-11147

---

src/Controller/PurchaseRequestController.php

Amélio frais de livraison : Si les frais sont gratuits, autoriser le 0 comme remplissage du champ

WIIS-11195

---

templates/mails/contents/mailThresholdReached.html.twig

Stock | Alerte | Mail - Nouveaux champs + mailto

WIIS-11202

---

src/Controller/Kiosk/KioskController.php
src/Controller/Settings/SettingsController.php
src/Entity/Kiosk.php
src/Entity/Utilisateur.php
src/EventListener/AnnotationListener.php
src/Repository/KioskTokenRepository.php

WIIS-11257

---

assets/js/pages/transport/request/index.js
src/Controller/Transport/RequestController.php
templates/transport/request/index.html.twig

WIIS-10478

---

public/js/pages/arrival/index.js
templates/arrivage/modalNewArrivage.html.twig

Revert "WIIS-11810"

---

src/Service/ReceptionService.php

show delivery fee but nothing in form

WIIS-11170

---

assets/js/pages/receipt-association/index.js

WIIS-12227

---

assets/js/pages/dispatch/show.js
assets/js/pages/pack/common.js
assets/js/pages/reception/show.js

WIIS-12236

---

templates/settings/trace/acheminements/champs_fixes.html.twig

WEB I Paramétrage I Acheminement I Champs fixes I Caractère spécial à enlever

WIIS-12274

---

assets/js/select2.js
src/Controller/SelectController.php
src/Service/DispatchService.php
src/Service/PackService.php

WIIS-12261

---

assets/js/pages/tracking-movement/tracking-movement.js
src/Controller/Api/Mobile/TrackingMovementController.php
src/Controller/TrackingMovementController.php
src/Entity/Tracking/Pack.php
src/Service/TrackingMovementService.php

WIIS-12127
